### ISSUE TITLE
[front] Change Bar Chart for D3.js

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#232]
Remove eCharts and move towards D3.js.

**Comment by felipovicc** [comment]
@kevinmamaqi  Still working on the issue. I have implemented the chart for the month view,  will add the yearly view and commit the changes.

**Comment by felipovicc** [comment]
New folder has been created named D3BarChart inside Charts so it doesn't override the previous graph.

Updated Barchart to use now D3.js to render graph data. Associated branch is ;  232-migrate-barchart-to-d3.

TO DO:

- Fix modal graphic display as the chart #id needs to be different for the modal window in order to render.
 
- Improve graphic render when resizing window.

**Comment by felipovicc** [comment]
Fixed modal graphic not displaying. Still to do:

-Improve graphic rendering when resizing and fix graphic size when resizing in modal window.
