### ISSUE TITLE
Add ad-edit endpoint

### ISSUE THREAD

**Issue by kevinmamaqi** [it-academyproject/ita-directory#432]
Allow users to edit the created ads.

**Comment by mariano-farace** [comment]
We found an issue related to posting to the database. For instance, when trying to post a new ad, we would get an error message "Unique constraint failed on the fields: ("id"). This makes no sense since @id is supposed to be unique by auto-incrementing it, and it is handled by the database.
 This problem was related to the seeding of the database with entries that had hard coded the "id" field on them, and the database starting it's auto-increment from the beginning (1) when trying to add a new entry, regardless of how many entries where already on that table.
The issue is now solved, by removing the hard-coded id from each seed file, and altering the loop that seeds the database.
Be aware that, if you have built your database prior to this change, you will still encounter the issue. What you can do is, drop at least one of the tables and the run the script "start-prisma"
![Screenshot from 2022-03-03 09-57-17](https://user-images.githubusercontent.com/38888451/156647750-11655e70-aaa8-459a-9291-eb457a71b39b.png)
